// ─── Shared TypeScript Interfaces ─────────────────────────
// Single source of truth for all data shapes.
// Imported by BOTH main process (IPC handlers, DAO) and renderer (stores, components).

export interface Snippet {
  id: string // UUID (generated by crypto.randomUUID())
  title: string // e.g., "Sad Piano Arpeggio"
  filePath: string // Absolute local path: /Users/name/Music/Memos/memo.m4a
  assetType: 'audio' | 'midi' | 'sheet' | 'video'
  keySignature: string | null // e.g., "C minor", "G major"
  bpm: number | null // e.g., 120
  mood: string | null // Freeform text, e.g., "Dark", "Cinematic", "Uplifting"
  createdAt: string // ISO 8601 timestamp
}

export interface Project {
  id: string // UUID
  title: string // e.g., "Neon Sonata"
  currentStageId: number // 1 through 15
  masterDirectory: string // Absolute path: /Users/name/Music/MaestroOS/Neon_Sonata/
  lastTouchedAt: string // ISO timestamp (updated by chokidar)
  createdAt: string // ISO timestamp
}

export interface ProjectAsset {
  id: string // UUID
  projectId: string // FK → projects.id
  stageId: number // FK → pipeline_stages.id
  filePath: string // Absolute local path
  assetType: string // File extension, e.g., '.logicx', '.wav', '.mp4'
  lastModified: string // ISO timestamp
}

export interface PipelineStage {
  id: number // 1 through 15
  stageName: string // e.g., "Audio Editing"
  gateRequirement: string | null // Comma-separated extensions, e.g., '.wav', '.mid,.pdf,.sib,.mscz'
  // null = conceptual stage (manual "Mark as Complete")
}

export interface ProjectSnippet {
  projectId: string // FK → projects.id
  snippetId: string // FK → snippets.id
}

// ─── Helper Types ─────────────────────────────────────────

export type CreateSnippetData = Omit<Snippet, 'id' | 'createdAt'>

export type CreateProjectData = {
  title: string
  masterDirectory: string
  snippetIds: string[]
}

export type LinkAssetData = Omit<ProjectAsset, 'id'>

// ─── Dashboard Types ──────────────────────────────────────

export interface ProjectStatus {
  projectId: string
  projectTitle: string
  currentStageId: number
  currentStageName: string
  gateRequirement: string | null
  lastTouchedAt: string
  daysSinceLastTouch: number
  isStale: boolean
  isTouchedToday: boolean
  recommendation: string
}
